#!/bin/zsh

for rcfile in ~/.z{shenv,shrc,login,logout}; 
do mv $rcfile ~/.zsh.backups  
    done



for rcfile in ~/.zsh/templates/z{shenv,shrc,login,logout}; 
do cp -fv $rcfile ~/.$rcfile:t 
    done
