#!/bin/zsh
## ZSHRC
## File is pointed to by .zshrc from default location, loads plugins

mydir=$(dirname "$0")

autoload -Uz compinit
compinit

autoload -Uz colors
colors

for f in $mydir/??_*.plugin.zsh; do
    source "$f"
done

for f in /usr/share/zsh/plugins/**/*.zsh; do
    . "$f"
done

source "$HOME"/.profile
