#!/bin/zsh
## ZSHRC
## File is pointed to by .zshrc from default location, loads plugins

# Create a variable storing the location the script is in...portably 
mydir=$(dirname "$0")

autoload -Uz compinit
compinit

autoload -Uz colors
colors

for f in $mydir/??_*.plugin.zsh; do
	source "$f"
done

if [[ -f /usr/share/zsh/plugins/**/*.zsh ]]; then
	for f in /usr/share/zsh/plugins/**/*.zsh; do
		. "$f" &>/dev/null
	done
fi

source "$HOME"/.profile
