#!/bin/zsh
## ZSHRC
## File is pointed to by .zshrc from default location,
## loads plugins
# --------------------------------------------------- #
# Create a variable storing the location the script is in...portably
mydir=$(dirname "$0")
# --------------------------------------------------- #
# Load the options necessary for the interactive shell
autoload -Uz compinit
compinit

autoload -Uz colors
colors

autoload -U zrecompile
# --------------------------------------------------- #
# Load local plugins from this directory
for f in $mydir/??_*.plugin.zsh; do
	#	zrecompile -pq "$f"
	source "$f"
done
# --------------------------------------------------- #
# Load any system wide zsh plugins, if they exist

if [[ -f /usr/share/zsh/plugins/**/*.zsh ]]; then
	for f in /usr/share/zsh/plugins/**/*.zsh; do
		. "$f" &>/dev/null
	done
fi

source "$HOME"/.profile
